
import { GoogleGenAI } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  // This is a fallback for development. In a real deployed environment,
  // process.env.API_KEY should be set.
  console.warn("API_KEY is not set. Using a placeholder. AI features will not work.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY || "YOUR_API_KEY_HERE" });

export const summarizeContent = async (content: string): Promise<string> => {
  if (!API_KEY || API_KEY === "YOUR_API_KEY_HERE") {
    return new Promise(resolve => setTimeout(() => resolve("This is a mock summary because the API key is not configured. The actual summary would be generated by Gemini, providing key insights and main topics from the document."), 1500));
  }
  
  try {
    const prompt = `Summarize the following study material. Focus on the key topics, concepts, and questions. Present it in a clear, concise format suitable for a student reviewing the material.

    Material to summarize:
    ---
    ${content}
    ---
    `;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });

    return response.text;
  } catch (error) {
    console.error("Error generating summary with Gemini:", error);
    return "Could not generate summary at this time. Please try again later.";
  }
};
